language: node_js
cache:
  directories:
  - node_modules
node_js: stable
branches:
  only:
  - master
install:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_187100459838_key -iv $encrypted_187100459838_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh "$DEPLOY_USER"@"$DEPLOY_HOST" -o StrictHostKeyChecking=no 'cd /data/smile-blog-nuxt && git pull && bash ./script/deploy.sh'
# notifications:
#   email:
#     recipients:
#     - qiushiming1997@gmail.com
#     on_success: always
#     on_failure: always
addons:
  ssh_known_hosts:
  - "$DEPLOY_HOST"
