language: node_js
cache:
  directories:
    - node_modules
node_js: stable
script: true
branches:
  only:
    - master
install:
  - skip
before_install:
  - openssl aes-256-cbc -K $encrypted_d11afb7726ff_key -iv $encrypted_d11afb7726ff_iv
    -in id_rsa.enc -out id_rsa -d
  - mv id_rsa ~/.ssh
  - chmod 600 ~/.ssh/id_rsa
after_success:
  - ssh "$DEPLOY_USER"@"$DEPLOY_HOST" -o StrictHostKeyChecking=no 'cd ./server/dashongdog-blog-nuxt
    && git pull && bash ./script/deploy.sh'
addons:
  ssh_known_hosts:
    - "$DEPLOY_HOST"
branches:
  only:
    - master